name: Extract HTML Info

on:
  push:
    branches: [ gh_pages ]
    paths:
    - '**.mlx'

jobs:
  extract-info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4

      - name: Get Changed HTML Files
        id: getfile
        run: |
          changed_files=$(git diff --name-only HEAD~1 HEAD | grep '\.html')
          echo "::set-output name=file::$changed_files"

      - name: Extract Info from HTML Files
        run: |
          for file in ${{ steps.getfile.outputs.file }}
          do
            python extract_info.py $file
          done
          
      - name: Commit and Push New File
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add .
          git commit -m "Add new HTML file" || echo "No changes to commit"
          git push origin gh_pages
